@echo off
echo Trying blank password...
"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -u root --password= -e "SELECT 'connected' AS status;" 2>&1
echo Trying password=mysql...
"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -u root -pmysql -e "SELECT 'connected' AS status;" 2>&1
echo Trying password=admin...
"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -u root -padmin -e "SELECT 'connected' AS status;" 2>&1
echo Trying password=password...
"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -u root -ppassword -e "SELECT 'connected' AS status;" 2>&1
echo Trying password=1234...
"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -u root -p1234 -e "SELECT 'connected' AS status;" 2>&1
echo Trying password=root123...
"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -u root -proot123 -e "SELECT 'connected' AS status;" 2>&1
